---
# file: roles/monitoring/tasks/03_add_elasticsearchrepo.yml

  - name: role monitoring | Add elastic search yum_repository
    yum_repository:
      name: elasticsearch
      description: ElasticSearch Repo
      file: ElasticSearch
      baseurl: https://spacewalk.lanathome.com/XMLRPC/GET-REQ/elasticsearch
      state: present
      enabled: yes
      gpgkey: https://spacewalk.lanathome.com/pub/GPG/RPM-GPG-KEY-LANATHOME
      gpgcheck: yes