---
# file: roles/monitoring/tasks/05_configure_filebeat.yml

  - name: role monitoring | Import elk01.lanathome.com SSL Cert
    copy:
      src: templates/elk01.lanathome.com.crt.j2
      dest: /etc/pki/ca-trust/source/anchors/elk01.lanathome.com
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: role monitoring | Update ca-trust
    shell: /bin/update-ca-trust

  - name: role monitoring | Configure and Start filebeat
    template:
      src: templates/filebeat.yml.j2
      dest: /etc/filebeat/filebeat.yml 
      owner: root
      group: root
      mode: 0600
      backup: yes

    # change line: 125.  host: "{{ my_kibanaserver }}:{{ my_kibanaserverport }}"
    # change line: 147   hosts: ["{{ my_elkserver }}:{{ my_elkport }}"]

  - name: role monitoring | Check if filebeat modules system is enabled
    shell: filebeat modules list system
    register: output

  #- debug: msg="{{ output.stdout.split('\n') }}"
  - debug: msg="{{ output.stdout.find('Enabled:\nsystem\n') != -1 }}"

  - name: role monitoring | Execute filebeat modules enable system
    shell: filebeat modules enable system
    ignore_errors: true
    when: output.stdout.find('Enabled:\nsystem\n')

  - name: role monitoring | Execute filebeat setup
    shell: filebeat setup
    notify: restart filebeat

    # "stdout": "Enabled:\nsystem\n\nDisabled:\napache2\nauditd\nelasticsearch\nicinga\niis\nkafka\nkibana\nlogstash\nmongodb\nmysql\nnginx\nosquery\npostgresql\nredis\ntraefik", 
    # "stdout_lines": [
    #     "Enabled:", 
    #     "system", 
    #     "", 
