---

- hosts: all
  become: yes

# based on documentation CIS_CentOS_Linux_7_Benchmark_v2.1.1.pdf
  tasks:

    - name: centos7 hardening | 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored)
      lineinfile:
        path: /etc/modprobe.d/CIS.conf
        create: yes
        state: present
        line: 'install cramfs /bin/true'

    - name: centos7 hardening | 1.1.1.2 Ensure mounting of freevxfs filesystems is disabled (Scored)
      lineinfile:
        path: /etc/modprobe.d/CIS.conf
        state: present
        line: 'install freevxfs /bin/true'

    - name: centos7 hardening | 1.1.1.3 Ensure mounting of jffs2 filesystems is disabled (Scored)
      lineinfile:
        path: /etc/modprobe.d/CIS.conf
        state: present
        line: 'install jffs2 /bin/true'

    - name: centos7 hardening | 1.1.1.3 Ensure mounting of jffs2 filesystems is disabled (Scored)
      lineinfile:
        path: /etc/modprobe.d/CIS.conf
        state: present
        line: 'install jffs2 /bin/true'

    - name: centos7 hardening | 1.1.1.4 Ensure mounting of hfs filesystems is disabled (Scored)
      lineinfile:
        path: /etc/modprobe.d/CIS.conf
        state: present
        line: 'install hfs /bin/true'

    - name: centos7 hardening | 1.1.1.5 Ensure mounting of hfsplus filesystems is disabled (Scored)
      lineinfile:
        path: /etc/modprobe.d/CIS.conf
        state: present
        line: 'install hfsplus /bin/true'

    - name: centos7 hardening | 1.1.1.6 Ensure mounting of squashfs filesystems is disabled (Scored)
      lineinfile:
        path: /etc/modprobe.d/CIS.conf
        state: present
        line: 'install hfsplus /bin/true'

    - name: centos7 hardening | 1.1.1.7 Ensure mounting of udf filesystems is disabled (Scored)
      lineinfile:
        path: /etc/modprobe.d/CIS.conf
        state: present
        line: 'install udf /bin/true'

    - name: centos7 hardening | 1.1.1.8 Ensure mounting of FAT filesystems is disabled (Scored)
      lineinfile:
        path: /etc/modprobe.d/CIS.conf
        state: present
        line: 'install vfat /bin/true'

    - name: centos7 hardening | 1.1.2 Ensure separate partition exists for /tmp (Scored)
      shell:
        mount | grep /tmp

    - name: centos7 hardening | 1.1.2a Ensure separate partition exists for /tmp (Scored)
      shell:
        systemctl unmask tmp.mount

    - name: centos7 hardening | 1.1.2b Ensure separate partition exists for /tmp (Scored)
      shell:
        systemctl enable tmp.mount

    - name: centos7 hardening | 1.1.2c Ensure separate partition exists for /tmp (Scored)
      blockinfile:
        path: /etc/systemd/system/local-fs.target.wants/tmp.mount
        block: |
          [Mount]
          What=tmpfs
          Where=/tmp
          Type=tmpfs
          Options=mode=1777,strictatime,noexec,nodev,nosuid

    - name: centos7 hardening | 1.1.3 Ensure nodev option set on /tmp partition (Scored)
      lineinfile:
        path: /etc/systemd/system/local-fs.target.wants/tmp.mount
        regexp: '^Options'
        line: 'Options=mode=1777,strictatime,noexec,nodev,nosuid'


    - name: centos7 hardening | 1.1.4 Ensure nosuid option set on /tmp partition (Scored)
      lineinfile:
        path: /etc/systemd/system/local-fs.target.wants/tmp.mount
        regexp: '^Options'
        line: 'Options=mode=1777,strictatime,noexec,nodev,nosuid'

    - name: centos7 hardening | 1.1.5 Ensure noexec option set on /tmp partition (Scored)
      lineinfile:
        path: /etc/systemd/system/local-fs.target.wants/tmp.mount
        regexp: '^Options'
        line: 'Options=mode=1777,strictatime,noexec,nodev,nosuid'

    - name: centos7 hardening | 1.1.6 Ensure separate partition exists for /var (Scored)
      shell:
        mount | grep "/var "

    - name: centos7 hardening | 1.1.7 Ensure separate partition exists for /var/tmp (Scored)
      shell:
        mount | grep "/var/tmp "

    - name: centos7 hardening | 1.1.8 Ensure nodev option set on /var/tmp partition (Scored)
      lineinfile:
        path: /etc/fstab
        regexp: '^/dev/mapper/rootvg-vartmpvol'
        line: '/dev/mapper/rootvg-vartmpvol /var/tmp                xfs     defaults,nodev        0 2'

    - name: centos7 hardening | 1.1.9 Ensure nosuid option set on /var/tmp partition (Scored)
      lineinfile:
        path: /etc/fstab
        regexp: '^/dev/mapper/rootvg-vartmpvol'
        line: '/dev/mapper/rootvg-vartmpvol /var/tmp                xfs     defaults,nodev,nosuid        0 2'

    - name: centos7 hardening | 1.1.10 Ensure noexec option set on /var/tmp partition (Scored)
      lineinfile:
        path: /etc/fstab
        regexp: '^/dev/mapper/rootvg-vartmpvol'
        line: '/dev/mapper/rootvg-vartmpvol /var/tmp                xfs     defaults,nodev,noexec        0 2'

    - name: centos7 hardening | 1.1.11 Ensure separate partition exists for /var/log (Scored)
      shell:
        mount | grep "/var/log "

    - name: centos7 hardening | 1.1.12 Ensure separate partition exists for /var/log/audit (Scored)
      shell:
        mount | grep "/var/log/audit "

    - name: centos7 hardening | 1.1.13 Ensure separate partition exists for /home (Scored)
      shell:
        mount | grep "/home "

    - name: centos7 hardening | 1.1.14 Ensure nodev option set on /home partition (Scored)


    - name: centos7 hardening | 1.1.15 Ensure nodev option set on /dev/shm partition (Scored)
    - name: centos7 hardening | 1.1.16 Ensure nosuid option set on /dev/shm partition (Scored)
    - name: centos7 hardening | 1.1.17 Ensure noexec option set on /dev/shm partition (Scored)
    - name: centos7 hardening | 1.1.18 Ensure nodev option set on removable media partitions (Not Scored)
    - name: centos7 hardening | 1.1.20 Ensure noexec option set on removable media partitions (Not Scored)
    - name: centos7 hardening | 1.1.21 Ensure sticky bit is set on all world-writable directories (Scored)
      shell:
        df --local -P | awk if '{ (NR!=1) print $6 }' | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t
    - name: centos7 hardening | 1.1.22 Disable Automounting (Scored)
      service:
        name: autofs
        state: disabled

    - name: centos7 hardening | 1.2.1 Ensure package manager repositories are configured (Not Scored)
      yum_repository:
        name: CentOS-Updates-local
        description: CentOS-7 - Updates from local repo
        baseurl: https://192.168.1.199/shares/CENTOS%2520UPDATES/7/updates/x86_64/
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
        repo_gpgcheck: no
        sslverify: no
      tags: updates

    - name: centos7 hardening | 1.2.1.1| Install the latest patches and security updates
      yum:
        name: '*'
        enablerepo: CentOS-Updates-local
        state: latest
      tags: updates



