---
# file: roles/common/tasks/05_disable_repo.yml

  - name: role common | disable repo
    template:
      src: templates/CentOS-Base.repo.j2
      dest: /etc/yum.repos.d/CentOS-Base.repo
      owner: root
      group: root
      mode: 0644
      backup: yes
    when:
      - ansible_distribution == "CentOS"
      - ansible_distribution_major_version == "7"

  - name: role common | disable repo CentOS-Base.repo
    template:
      src: templates/CentOS-Base.repo.j2
      dest: /etc/yum.repos.d/CentOS-Base.repo
      owner: root
      group: root
      mode: 0644
      backup: yes
    when:
      - ansible_distribution == "CentOS"
      - ansible_distribution_major_version == "8"

  - name: role common | disable repo CentOS-AppStream
    template:
      src: templates/CentOS-AppStream.repo.j2
      dest: /etc/yum.repos.d/CentOS-AppStream.repo
      owner: root
      group: root
      mode: 0644
      backup: yes
    when:
      - ansible_distribution == "CentOS"
      - ansible_distribution_major_version == "8"

  - name: role common | disable repo CentOS-Extras
    template:
      src: templates/CentOS-Extras.repo.j2
      dest: /etc/yum.repos.d/CentOS-Extras.repo
      owner: root
      group: root
      mode: 0644
      backup: yes
    when:
      - ansible_distribution == "CentOS"
      - ansible_distribution_major_version == "8"

  # - name: role common | yum-clean-metadata
  #   command: yum clean metadata
  #   args:
  #     warn: no
