---
# file: roles/common/tasks/05_install_packages.yml

  - name: role common | get GPG key
    #command: /bin/rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    command: /bin/rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial

  - name: role common | Install additional packages
    yum:
      name: "{{ item }}"
      state: present 
    loop:
      - wget
      - rhn-setup
      - rhn-check
      - rhnlib
      - rhn-client-tools
      - rhnsd
