---
# file: roles/common/tasks/07_rhn_register

  - name: role common | Subscribe Centos7 host to spacewalk 
    shell: /sbin/rhnreg_ks --serverUrl=https://spacewalk.lanathome.com/XMLRPC --sslCACert=/usr/share/pki/ca-trust-source/anchors/lanathome.crt --activationkey=1-01a0cb409e45dc5766b067f2a6c27e0e --force
    when:
      - ansible_distribution == "CentOS"
      - ansible_distribution_major_version == "7"

  - name: role common | Subscribe Centos8 host to spacewalk
    shell: /sbin/rhnreg_ks --serverUrl=https://spacewalk.lanathome.com/XMLRPC --sslCACert=/usr/share/pki/ca-trust-source/anchors/lanathome.crt --activationkey=1-81a22a5adc9204ed1a3976670c388574 --force
    when:
      - ansible_distribution == "CentOS"
      - ansible_distribution_major_version == "8"
