---
# roles/common/tasks/02_set_locale.yml

  - name: role common | Set LANG, LC_ALL
    blockinfile:
      path: /etc/environment
      create: yes
      block: |
        LANG=en_US.utf-8
        LC_ALL=en_US.utf-8