---
# roles/common/tasks/03_create_ngr.yml

  - name: role common | Set authorized key took from grosshaa's ssh
    authorized_key:
      user: ngr
      state: present
      key: "{{ lookup('file', '/Users/ngr/.ssh/id_rsa.pub') }}"