---
# file: roles/common/tasks/05_disable_repo.yml

  - name: role common | disable repo
    template:
      src: templates/CentOS-Base.repo.j2
      dest: /etc/yum.repos.d/CentOS-Base.repo
      owner: root
      group: root
      mode: 0644
      backup: yes


  - name: role common | yum-clean-metadata
    command: yum clean metadata
    args:
      warn: no
