---
# file: roles/common-centos8/tasks/01_set_dns.yml


  - name: role common-centos8 | Set DNS
    blockinfile:
      path: /etc/resolv.conf
      create: yes
      block: |
        nameserver 192.168.1.36
        search lanathome.com
