---
# file: roles/common-centos8/tasks/02_disable_ipv6.yml

  - name: role common-centos8  | disable ipv6 net.ipv6.conf.all.disable_ipv6 = 1
    sysctl:
      name: net.ipv6.conf.all.disable_ipv6
      value: 1
      state: present
      reload: yes

  - name: role common-centos8 | disable ipv6 net.ipv6.conf.default.disable_ipv6 = 1
    sysctl:
      name: net.ipv6.conf.default.disable_ipv6
      value: 1
      state: present
      reload: yes