---
# file: roles/common-centos8/tasks/08_enable_rhn_channel.yml

  - name: role common-centos8 | enable rhn_channel centos-8-appstream-x86_64-1905
    shell:
      rhn-channel --add --channel=centos-8-appstream-x86_64-1905 --user=register --password=register

  - name: role common-centos8 | enable rhn_channel centos-8-extras-x86_64-1905
    shell:
      rhn-channel --add --channel=centos-8-extras-x86_64-1905 --user=register --password=register

  - name: role common-centos8 | enable rhn_channel centos-8-powertools-x86_64-1905
    shell:
      rhn-channel --add --channel=centos-8-powertools-x86_64-1905 --user=register --password=register

  - name: role common-centos8 | enable rhn_channel centos8-elasticsearch-7.x
    shell:
     rhn-channel --add --channel=centos8-elasticsearch-7.x --user=register --password=register

  - name: role common-centos8 | enable rhn_channel centos8-spacewalk-2.9-client
    shell:
      rhn-channel --add --channel=centos8-spacewalk-2.9-client --user=register --password=register